Repository serve-now/serveEase-frontend, pull requests merged in 2025-10, with the labels that each got.

#24 Feat/admin : pos/products 하위 Modal 관련 direct 접근 및 새로고침 시 정상화
  src/app/(private)/pos/(shell-layout)/products/@modal/(.)[productId]/edit/page.tsx
  src/app/(private)/pos/(shell-layout)/products/@modal/(.)new/page.tsx
  src/app/(private)/pos/(shell-layout)/products/[productId]/edit/page.tsx
  src/app/(private)/pos/(shell-layout)/products/[productId]/page.tsx
  src/app/(private)/pos/(shell-layout)/products/new/page.tsx
  src/app/(private)/pos/(shell-layout)/products/newCategory/page.tsx
  src/app/(private)/pos/(shell-layout)/products/page.tsx
Labels: bug

#29 fix: 메뉴별 총 가격 표시 및 주문 생성 오류 수정
  src/app/(private)/pos/tables/[tableId]/page.tsx
  src/hooks/useTables.ts
Labels: refactor

#30 refactor: 1차 리팩토링: 쿼리 명시화, 타입 분리, 특수 파일 도입(error/not-found/loading)
  src/app/(private)/pos/(shell-layout)/loading.tsx
  src/app/(private)/pos/tables/[tableId]/page.tsx
  src/app/api/api.ts
  src/app/api/menu.ts
  src/app/api/order.ts
  src/app/api/tables.ts
  src/app/error.tsx
  src/app/not-found.tsx
  src/components/ExistingOrderList.tsx
  src/hooks/useMenus.ts
  src/hooks/useOrder.ts
  src/hooks/useTables.ts
  src/types/menu.ts
  src/types/order.ts
  src/types/table.ts
Labels: refactor

#28 Feat/fix: 수정 관련 사항 해결
  global.d.ts
  src/app/(private)/pos/(shell-layout)/layout.tsx
  src/app/(private)/pos/(shell-layout)/products/page.tsx
  src/app/layout.tsx
  src/app/signup/page.tsx
  src/hooks/useCategories.ts
  src/hooks/useProducts.ts
  src/hooks/useSignup.ts
  src/lib/productSearchFilters.ts
  src/styles/globals.css
  tsconfig.json
Labels: bug, feat, refactor, style

#33 feat: 토스페이먼츠 결제 기능 구현 - 결제창 연동 및 승인 API 연결
  package-lock.json
  package.json
  src/app/(private)/pos/(shell-layout)/payment/fail/route.ts
  src/app/(private)/pos/(shell-layout)/payment/success/page.tsx
  src/app/(private)/pos/tables/[tableId]/page.tsx
  src/app/api/payments.ts
  src/components/page/OrderCheck.tsx
  src/hooks/usePayment.ts
Labels: feat

#34 refactor: 토스페이먼츠 결제 로직 개선, 상품 갱신 버그 해결 및 쿼리 최적화
  src/app/(private)/pos/(shell-layout)/payment/success/page.tsx
  src/app/(private)/pos/tables/[tableId]/page.tsx
  src/app/api/payments.ts
  src/components/page/OrderCheck.tsx
  src/hooks/payment/usePayment.ts
  src/hooks/payment/usePaymentFail.ts
  src/hooks/payment/useTossPayments.ts
  src/hooks/useOrder.ts
  src/hooks/usePayment.ts
  src/hooks/useProducts.ts
  src/lib/paymentUtils.ts
  src/types/order.ts
  src/types/payment.ts
Labels: refactor

#35 refactor: 전반적인 접근성 및 SEO 리팩토링 및 파비콘 설정
  src/app/(private)/pos/(shell-layout)/page.tsx
  src/app/(private)/pos/(shell-layout)/payment/success/page.tsx
  src/app/(private)/pos/(shell-layout)/tables/page.tsx
  src/app/(private)/pos/tables/[tableId]/orders/page.tsx
  src/app/(private)/pos/tables/[tableId]/page.tsx
  src/app/apple-touch-icon.png
  src/app/favicon.ico
  src/app/icon.png
  src/components/page/OrderCheck.tsx
  src/components/page/TableSetup.tsx
  src/hooks/useTables.ts
Labels: refactor, style
