Repository serve-now/serveEase-frontend, pull requests merged in 2025-09, with the labels that each got.

#1 feat: 공통 컴포넌트 작업 - Header, Logo, Input, Button
  components.json
  package-lock.json
  package.json
  src/components/Button.tsx
  src/components/Header.tsx
  src/components/Input.tsx
  src/components/Logo.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/lib/utils.ts
  src/styles/globals.css
Labels: feat, style

#4 feat: 공통 컴포넌트(ModeCard, TableCard, MenuCard, ProductItem, BackButton) 및 페이지 레이아웃 개발
  src/app/(private)/pos/layout.tsx
  src/components/BackButton.tsx
  src/components/MenuButton.tsx
  src/components/ModeCard.tsx
  src/components/ProductItem.tsx
  src/components/TableCard.tsx
  src/components/ui/card.tsx
  src/styles/globals.css
Labels: feat, style

#6 feat: 메인 페이지 UI 구현 및 페이지 레이아웃 수정
  src/app/(private)/pos/layout.tsx
  src/app/(private)/pos/page.tsx
  src/components/ModeCard.tsx
Labels: feat, style

#7 feat: 결제 성공 페이지 UI 구현
  src/app/(private)/pos/payment/success/page.tsx
Labels: feat, style

#8 feat: 테이블 페이지 UI 구현
  src/app/(private)/pos/tables/page.tsx
  src/components/TableCard.tsx
Labels: feat, style

#10 Feat: 상품관리 페이지 추가
  src/app/(private)/pos/(shell-layout)/products/@modal/(.)[productId]/edit/page.tsx
  src/app/(private)/pos/(shell-layout)/products/@modal/(.)new/page.tsx
  src/app/(private)/pos/(shell-layout)/products/page.tsx
Labels: style

#12 feat: 회원가입 페이지 레이아웃 구현
  src/app/signup/layout.tsx
  src/app/signup/page.tsx
Labels: style

#15 feat: 테이블 페이지 조회 및 페이지네이션 기능 구현
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  src/app/(private)/pos/(shell-layout)/tables/page.tsx
  src/app/api/tables.ts
  src/app/providers.tsx
  src/components/TableCard.tsx
  src/hooks/useTables.ts
  src/lib/axios.ts
Labels: feat, style

#16 Feat
  package-lock.json
  package.json
  src/app/api/login.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/hooks/useLogin.ts
  src/lib/axios.ts
Labels: feat

#19 feat: 주문 기능 추가 및 쿼리 함수(useCategories, useMenus) 옵션 수정
  src/app/(private)/pos/tables/[tableId]/page.tsx
  src/app/api/order.ts
  src/app/api/pos.ts
  src/components/CategoryTab.tsx
  src/components/ExistingOrderList.tsx
  src/hooks/useCategories.ts
  src/hooks/useMenus.ts
  src/hooks/useOrder.ts
  src/hooks/useOrderCart.ts
  src/hooks/useTables.ts
Labels: feat

#20 feat: 주문 기능 구현(주문 내역 조회, 생성, 재주문, 취소) 및 API 변경 대응
  src/app/(private)/pos/(shell-layout)/tables/page.tsx
  src/app/(private)/pos/tables/[tableId]/page.tsx
  src/app/api/categories.ts
  src/app/api/login.ts
  src/app/api/menu.ts
  src/app/api/order.ts
  src/app/api/store.ts
  src/app/api/tables.ts
  src/app/layout.tsx
  src/components/ExistingOrderList.tsx
  src/components/MenuButton.tsx
  src/hooks/useOrder.ts
  src/hooks/useTables.ts
  src/lib/error.ts
Labels: feat
